### ISSUE TITLE
HTML5 boilerplate

### ISSUE THREAD

**Issue by stefanvermaas** [NicholasRBowers/CSS-Slider-Menu#4]
Do you really want to use the HTML5 boilerplate. I agree with this talk of Rachel Andrew: http://www.rachelandrew.co.uk/archives/2012/03/21/stop-solving-problems-you-dont-yet-have/

What you think about?

**Comment by NicholasRBowers** [comment]
The HTML5 Boilerplate is solid.  Offers a very nice experience and normalization across most browsers.  The only reason I would not use it, would be the same reason I don't use frameworks - document size.  Since we're optimizing this for mobile, we may not need everything in the boilerplate, and it may just slow down the page.  I will take bits and pieces from it though - maybe some normalization (for mainly the content div area), the HTML5 Shiv/Shim, and a few of the settings in the <head> for optimization.  We don't need all of it, to be sure, I just didn't want people thinking that body, div { padding: 0; margin: 0} was the extent of my normalization!
